### ISSUE TITLE
The speed of cuosqp

### ISSUE THREAD

**Issue by ztjsw** [osqp/cuosqp#5]
Hi there,
Thanks for your great work. 
I have ran the code of osqp in CPU. I'm wondering if the solver of GPU will be faster than CPU? If yes, I may try upgrade my solver to gpu.

**Comment by gbanjac** [comment]
The GPU-based implementation is expected to be faster on very large problem instances. You can take a look at numerical results (Section 7) of [this paper](https://doi.org/10.1016/j.jpdc.2020.05.021).

**Comment by ztjsw** [comment]
Thanks. The problem size N is the dimension of the matrix `P` in `Equality` problem?

**Comment by gbanjac** [comment]
No, `N` is defined in Section 6.1 as the total number of nonzero elements in matrices `P` and `A`.

**Comment by ztjsw** [comment]
OK. I will read the other details in paper and test it with my algorithm.
Thanks again.
