### ISSUE TITLE
Why cuosqp is much slower than osqp when problem size is small?

### ISSUE THREAD

**Issue by Turoad** [osqp/cuosqp#7]
I compare the cuosqp with osqp, the source code is `examples/osqp_demo.c`. But it seems the cuosqp (6.31e-01s) is much slower than osqp (1.32e-04s).
gpu:
![image](https://user-images.githubusercontent.com/36562593/124570357-61e8fc00-de79-11eb-89e1-ba460e419b29.png)
cpu:
![image](https://user-images.githubusercontent.com/36562593/124570292-539ae000-de79-11eb-9c6d-8e427add1cce.png)
The paper shows the main difference between OSQP and cuOSQP as follows: 
![image](https://user-images.githubusercontent.com/36562593/124571888-c5275e00-de7a-11eb-97d2-43328715556a.png)
I'm wondering if they use the same method (for example, they all use direct linear system), will the cuOSQP be faster than OSQP?

**Comment by gbanjac** [comment]
From [this paper](https://doi.org/10.1016/j.jpdc.2020.05.021):

> Note, however, that small problems cannot be accelerated well with GPUs, as there is not enough work to keep the GPU busy and a kernel launch and data transfer come with a constant overhead that cannot be amortized.

If both OSQP and cuOSQP used the same method, cuOSQP would still be slower for smaller problems.
